### PR TITLE
to resolve the issue: 'remove chromedriver.exe' and some improvements in css

### PR DESCRIPTION
**Pull request by subhrapaladhi**
- i have removed the chromedriver.exe
mentioned it in readme.md with download link
and have also added it to .gitignore

- i have also made some changes in the css.

### CODE REVIEW

**Comment by L04DB4L4NC3R** [comment]
@subhrapaladhi resolve the conflicts it has with the master branch

**Comment by subhrapaladhi** [comment]
image

@L04DB4L4NC3R  I am going to the resolve conflicts page and it is getting stuck on this page. nothing is showing up.

**Comment by L04DB4L4NC3R** [comment]
@subhrapaladhi Take a pull from master, resolve conflicts, then push

**Comment by subhrapaladhi** [comment]
@L04DB4L4NC3R I guess the problem is solved. There are no more conflicts

**Pull request merged**
