### PR TITLE
readme

### PR DESCRIPTION
**Pull request by subhrapaladhi**

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@subhrapaladhi 

Why did you close this?
Are you gonna send another PR with updated `README.md`

**Review by vinitshahdeo — COMMENTED** [review]
@subhrapaladhi 

Please provide some more context.

**Comment by subhrapaladhi** [comment]
i thought it would be better if instead of just a readme file i also add a prototype for the webpage. i will pull request as soon as i am done with that.

**Comment by vinitshahdeo** [comment]
@subhrapaladhi, That's nice!

**Please follow `README.md` guidelines.**

**Comment by subhrapaladhi** [comment]
ok.
thankyou @vinitshahdeo

**Review by vinitshahdeo — APPROVED** [review]

**Review by vinitshahdeo — APPROVED** [review]

**Comment by vinitshahdeo** [comment]
@subhrapaladhi 
Provide an appropriate title & description for the PR.

**Review by vinitshahdeo — APPROVED** [review]
Perfect 👍

**Comment by subhrapaladhi** [comment]
@vinitshahdeo I have two doubts

1. although you have approved all the pull requests, the files have not updated in the CodeChefVIT/research-paper-query. Why is this happening I have also attached an image of the same
image


2. what I commit in my branch(subhrapaladhi/research-paper query) automatically send an approval request to this branch(CodeChefVIT/research-paper-query) in this pull request session. Do to need to close this pull request session before I can put a new pull request?

**Pull request merged**
