### PR TITLE
The website is working

### PR DESCRIPTION
**Pull request by subhrapaladhi**
this is the link of the website: https://research-paper-query-cc.herokuapp.com/

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
Good job @subhrapaladhi :)

Take help from any front  developer and beautify the home page if you have time.

**Review by vinitshahdeo — COMMENTED** [review]
**Some commit messages make no sense.**  Some random texts `fdsys` are there! This is quite misleading. 

Please make sure that commit messages are appropriate and each commit is atomic. The commit message should exactly explain the changes made. 

_Rest LGTM!_

Good job @subhrapaladhi :)

**Comment by L04DB4L4NC3R** [comment]
@subhrapaladhi Follow the guidelines [here](https://github.com/CodeChefVIT/getting-started).

**Comment by subhrapaladhi** [comment]
@vinitshahdeo, @L04DB4L4NC3R I will take care the comments from next time and will get in touch with a frontend developer ASAP

**Comment by L04DB4L4NC3R** [comment]
> @vinitshahdeo, @L04DB4L4NC3R I will take care the comments from next time and will get in touch with a frontend developer ASAP

We have assigned *Kunal* to be your frontend guy. Do communicate with him. Get in touch with the design team to decide upon an ideal interface for the final public deployment.

**Comment by subhrapaladhi** [comment]
@L04DB4L4NC3R i have taked with kunal and he said he will start his work from today

**Pull request merged**
